echo -e "\033[0;34m"
echo "    A        DDDDDD        A       M       M      A      N       N"
echo "   A:A       D      D     A:A      M M  M  M     A:A     N  N    N"
echo "  A   A      D      D    A   A     M   M   M    A   A    N   N   N"
echo " A:AAA:A     D      D   A:AAA:A    M       M   A:AAA:A   N    N  N"
echo "A       A    DDDDDD    A       A   M       M  A       A  N       N"
echo -e "\033[0;32m"
echo -e "\t\t\t\t\t\t\tadamanlab.xyz"
echo -e "\e[0m"
