echo -e "\033[0;34m"
echo "     A:::   DDDD   AAA   M   M  AAA   N   N"
echo "    A:  :A D   D A   A  MM MM A   A  NN  N"
echo "   A:   AA D   D AAAAAA M M M M AAAAAA N N N"
echo "  A:  :A  D   D A   A  M   M  A   A  N  NN"
echo " A:::   A DDDD A   A M   M  A   A  N   N"
echo -e "\033[0;32m"
echo "                                      adaman.xyz"
echo -e "\e[0m"
